### PR TITLE
Laravel Cypress 0.2.1 Version & Whole Project Upgraded into Laravel 8 version

### PR DESCRIPTION
**Pull request by JunaidJaved248**
Hi @NoelDeMartin , I have upgraded the laravel Cypress Version and Whole project Upgraded into Laravel 8 according to Laravel Official Docs!

### CODE REVIEW

**Comment by NoelDeMartin** [comment]
Hi there, thanks for opening the PR!

The changes seem fine, but there are a couple of things I'd like to have before merging this:

- Can you rebase your commits? There are some automated tests that should be run, but they weren't configured properly to run on pull requests. If you rebase, it should work.
- Instead of changing only the bare minimum to upgrade, can you update the rest of the files that have changed? Given that this is an example project, I'd like to keep it as similar as possible to a new Laravel project. You can use Github's [comparison tool](https://github.com/laravel/laravel/compare/7.x...master) to see the changes. It isn't necessary to change everything, for example you probably won't need to change the welcome screen because it'd break the tests. But I'm particularly interested in using the new model factories that were introduced in Laravel 8.

**Comment by JunaidJaved248** [comment]
You mean that I have create new branch and push their updated version with limited changes then push again?
Correct me if I am wrong?

**Comment by NoelDeMartin** [comment]
You can do something that is called [git rebase](https://git-scm.com/book/en/v2/Git-Branching-Rebasing) an then use `git push --force` to update this PR.

If you don't know how to do it and you prefer to open a new PR with a different branch that's ok :).

**Comment by JunaidJaved248** [comment]
@NoelDeMartin Check Now Please if still not done yet!! Then i will open new PR OK

**Comment by JunaidJaved248** [comment]
PR is Updated Now!!

**Comment by NoelDeMartin** [comment]
I still see the same thing here, I've looked at your fork and it doesn't have any other branches either so something must have gone wrong. Check if you still have local changes.

**Comment by JunaidJaved248** [comment]
OK Let me done, By opening new PR by New Branch

**Comment by JunaidJaved248** [comment]
@NoelDeMartin  Check Now!! 
Please I have also created New PR!
Let me know if still not done

**Comment by NoelDeMartin** [comment]
Ok thanks for doing the rebase!

We can see now that tests are failing. I think the reason is that you haven't changed the User model factory as I mentioned. Old factories have been deprecated, so they are not supported in Laravel 8 unless you install a legacy package.

Can you take a look at that?

**Comment by JunaidJaved248** [comment]
OK Give me few min i will install it!!
Should install it on this PR or newly created other PR?

**Comment by JunaidJaved248** [comment]
check now please i have updated on JJ branch!
Gave me feedback!!

**Pull request merged**
